services:
  directus_db:
    image: postgres:15
    container_name: directus_db
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: directus
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  directus_app:
    image: directus/directus:latest
    container_name: directus_app
    ports:
      - "8055:8055"
    environment:
      KEY: 'random-key-here-change-me'
      SECRET: 'random-secret-here-change-me'
      DB_CLIENT: 'pg'
      DB_HOST: directus_db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: password
    volumes:
      - uploads:/directus/uploads
    depends_on:
      - directus_db
volumes:
  db_data:
  uploads: